package com.wqy.ganhuo.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;

/**
 * Entity mapped to table ANDROID_CACHE.
 */
public class AndroidCache {

    private Long id;
    private String result;
    private String page;

    public AndroidCache() {
    }

    public AndroidCache(Long id) {
        this.id = id;
    }

    public AndroidCache(Long id, String result, String page) {
        this.id = id;
        this.result = result;
        this.page = page;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getPage() {
        return page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        AndroidCache that = (AndroidCache) o;
        String thatResult = that.getResult();
        String thisResult = this.getResult();
        if(thatResult == null || thisResult == null)
            return false;
        JSONArray thatArray = JSON.parseArray(thatResult);
        JSONArray thisArray = JSON.parseArray(thisResult);
        if(thatArray == null || thisArray == null)
            return false;
        if(thatArray.size() != thisArray.size())
            return false;
        if(!thatArray.getJSONObject(0).getString("objectId").equals(thisArray.getJSONObject(0).getString("objectId"))) {
            return false;
        }

        return true;

    }

    @Override
    public int hashCode() {
        int result1 = id != null ? id.hashCode() : 0;
        result1 = 31 * result1 + (result != null ? result.hashCode() : 0);
        result1 = 31 * result1 + (page != null ? page.hashCode() : 0);
        return result1;
    }
}
