package com.wqy.ganhuo.greendao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wqy.ganhuo.greendao.AndroidCache;
import com.wqy.ganhuo.greendao.IOSCache;
import com.wqy.ganhuo.greendao.PictureCache;
import com.wqy.ganhuo.greendao.VideoCache;
import com.wqy.ganhuo.greendao.Favorite;

import com.wqy.ganhuo.greendao.AndroidCacheDao;
import com.wqy.ganhuo.greendao.IOSCacheDao;
import com.wqy.ganhuo.greendao.PictureCacheDao;
import com.wqy.ganhuo.greendao.VideoCacheDao;
import com.wqy.ganhuo.greendao.FavoriteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig androidCacheDaoConfig;
    private final DaoConfig iOSCacheDaoConfig;
    private final DaoConfig pictureCacheDaoConfig;
    private final DaoConfig videoCacheDaoConfig;
    private final DaoConfig favoriteDaoConfig;

    private final AndroidCacheDao androidCacheDao;
    private final IOSCacheDao iOSCacheDao;
    private final PictureCacheDao pictureCacheDao;
    private final VideoCacheDao videoCacheDao;
    private final FavoriteDao favoriteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        androidCacheDaoConfig = daoConfigMap.get(AndroidCacheDao.class).clone();
        androidCacheDaoConfig.initIdentityScope(type);

        iOSCacheDaoConfig = daoConfigMap.get(IOSCacheDao.class).clone();
        iOSCacheDaoConfig.initIdentityScope(type);

        pictureCacheDaoConfig = daoConfigMap.get(PictureCacheDao.class).clone();
        pictureCacheDaoConfig.initIdentityScope(type);

        videoCacheDaoConfig = daoConfigMap.get(VideoCacheDao.class).clone();
        videoCacheDaoConfig.initIdentityScope(type);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        androidCacheDao = new AndroidCacheDao(androidCacheDaoConfig, this);
        iOSCacheDao = new IOSCacheDao(iOSCacheDaoConfig, this);
        pictureCacheDao = new PictureCacheDao(pictureCacheDaoConfig, this);
        videoCacheDao = new VideoCacheDao(videoCacheDaoConfig, this);
        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);

        registerDao(AndroidCache.class, androidCacheDao);
        registerDao(IOSCache.class, iOSCacheDao);
        registerDao(PictureCache.class, pictureCacheDao);
        registerDao(VideoCache.class, videoCacheDao);
        registerDao(Favorite.class, favoriteDao);
    }
    
    public void clear() {
        androidCacheDaoConfig.getIdentityScope().clear();
        iOSCacheDaoConfig.getIdentityScope().clear();
        pictureCacheDaoConfig.getIdentityScope().clear();
        videoCacheDaoConfig.getIdentityScope().clear();
        favoriteDaoConfig.getIdentityScope().clear();
    }

    public AndroidCacheDao getAndroidCacheDao() {
        return androidCacheDao;
    }

    public IOSCacheDao getIOSCacheDao() {
        return iOSCacheDao;
    }

    public PictureCacheDao getPictureCacheDao() {
        return pictureCacheDao;
    }

    public VideoCacheDao getVideoCacheDao() {
        return videoCacheDao;
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

}
