package com.wqy.ganhuo.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IOSCACHE.
 */
public class IOSCache {

    private Long id;
    private String result;
    private String page;

    public IOSCache() {
    }

    public IOSCache(Long id) {
        this.id = id;
    }

    public IOSCache(Long id, String result, String page) {
        this.id = id;
        this.result = result;
        this.page = page;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getPage() {
        return page;
    }

    public void setPage(String page) {
        this.page = page;
    }

}
